mapapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired





class PostForm(FlaskForm):
	title = StringField('title', validators=[DataRequired()])
	content = TextAreaField('Content', validators= [DataRequired()])
	submit = SubmitField('Post')


mapapp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from mapapp.models import User
from flask_login import current_user




class RegistrationForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
	email = StringField('Email', validators= [DataRequired()])
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Sign Up')
	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user:
			raise ValidationError('The username already exists')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError('The email already exists')

class LoginForm(FlaskForm):
	email = StringField('Email', validators= [DataRequired()])
	password = PasswordField('Password', validators=[DataRequired()])
	remember = BooleanField('Remember Me')
	submit = SubmitField('Login')

class UpdateAccountForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
	email = StringField('Email', validators= [DataRequired()])
	submit = SubmitField('Update')
	picture = FileField('Update Profile Pic', validators=[FileAllowed(['jpg', 'png'])])
	def validate_username(self, username):
		if username.data != current_user.username:

			user = User.query.filter_by(username=username.data).first()
			if user:
				raise ValidationError('The username already exists')

	def validate_email(self, email):
		if email.data != current_user.email:

			user = User.query.filter_by(email=email.data).first()
			if user:
				raise ValidationError('The email already exists')


mapapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from mapapp.config import Config


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'



def create_app(config_class=Config):

	app=Flask(__name__)
	app.config.from_object(Config)

	db.init_app(app)
	bcrypt.init_app(app)
	login_manager.init_app(app)

	from mapapp.users.routes import users
	from mapapp.posts.routes import posts
	from mapapp.main.routes import main
	from mapapp.errors.handlers import errors
	app.register_blueprint(users)
	app.register_blueprint(posts)
	app.register_blueprint(main)
	app.register_blueprint(errors)

	return app

mapapp/main/routes.py
from flask import render_template, url_for, redirect, flash, request, Blueprint
from mapapp import db
from mapapp.posts.forms import PostForm
from mapapp.models import Post
from flask_login import current_user

main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
@main.route('/home', methods=['GET', 'POST'])
def home():
	form = PostForm()
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Comment was added successfully', 'success')
		return redirect(url_for('main.home'))
	return render_template('home.html', title='Home', form=form, posts=posts)


mapapp/posts/routes.py
from flask import render_template, url_for, redirect, flash, request, Blueprint, abort
from mapapp import db
from mapapp.posts.forms import PostForm
from mapapp.models import Post
from flask_login import current_user, login_required



posts = Blueprint('posts', __name__)

@login_required
@posts.route("/post", methods=['GET', 'POST'])
def post():
	form=PostForm()
	return render_template('post.html', title='Post Comment', form=form)



@login_required
@posts.route("/update_post/<int:post_id>", methods=['GET', 'POST'])
def update_post(post_id):
	form=PostForm()
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)

	if form.validate_on_submit():
		flash('post Updated')
		post.content = form.content.data
		post.title = form.title.data
		db.session.commit()
		return redirect(url_for('main.home'))
	elif request.method =='GET':
		form.content.data = post.content
		form.title.data = post.title
	return render_template('update_post.html', title='Update_Post', form=form)



@login_required
@posts.route("/delete_post/<int:post_id>")
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	return redirect(url_for("main.home"))


mapapp/users/routes.py
from flask import render_template, url_for, redirect, flash, request, Blueprint
from mapapp import db, bcrypt
from mapapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from mapapp.models import User
from flask_login import login_user, current_user, logout_user, login_required
from mapapp.users.utils import save_picture


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	else:

		form = RegistrationForm()
		if form.validate_on_submit():
			hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
			user = User(username=form.username.data, email=form.email.data, password=hashed_password)
			db.session.add(user)
			db.session.commit()
			flash(f'Your account has been created successfully', 'success')
			return redirect(url_for('users.login'))
	
	return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			flash('The user logged in successfully')
			return redirect(url_for('main.home'))
	return render_template('login.html', title='Log In', form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@login_required
@users.route("/account", methods=['GET', 'POST'])
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		current_user.username = form.username.data
		current_user.email = form.email.data
		if form.picture.data:
			current_user.image_file = save_picture(form.picture.data)
		db.session.commit()
		flash('User account updated successfully')
		return redirect(url_for('main.home'))
	elif request.method == "GET":
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='images/' + current_user.image_file)
	flash(image_file)
	return render_template('account.html', title='account', form=form, image_file=image_file)

mapapp/templates/account.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section">
  		<div class="media">
    		<img class="rounded-circle account-img" src={{image_file}}>
    		<div class="media-body">
      			<h2 class="account-heading">{{current_user.username}}</h2>
      			<p class="text-secondary">{{current_user.email}}</p>
    		</div>
  		</div>
  	<div class='content-section'>
	<form method="POST" action="" enctype="multipart/form-data">
		{{form.hidden_tag()}}
		<fieldset class='form-group'>
			<legend class="border-bottom mb-4"> Account Information </legend>
			<div class='form-group'>
				{{ form.username.label(class="form-control-label")}}
				{%if form.username.errors %}
					{{ form.username(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.username.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.username(class="form-control form-control-label-lg")}}
				{%endif%}
			</div>

			<div class='form-group'>
				{{ form.email.label(class="form-control-label")}}
				{%if form.email.errors %}
					{{ form.email(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.email.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.email(class="form-control form-control-label-lg")}}
				{%endif%}				
				
			</div>
			<div class='form-group'>
				{{ form.picture.label()}}
				{{ form.picture(class='form-control-file')}}
				{%if form.picture.errors %}
					{% for error in form.picture.errors%}
						<span class='text-danger'> {{error}} </span> </br>
					{%endfor%}
				{%endif%}
				
			</div>

		</fieldset>

		<div class='form-group'>
			{{form.submit(class='btn btn-outline-info')}}
		</div>
	</form>
	<div class='border-top pt-3'>
		<small class='text-muted'>
			Already have an account? <a class='ml-2' href="{{url_for('users.login')}}"> Sign In</a>
		</small> 
	</div>
</div>

	</div>
{%endblock content%}



mapapp/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{%if current_user.is_authenticated%}


<div class='row'>

	<div class="col-md-8">
		{% for post in posts.items %}
		<article>
		<div class='container post-group'> 

			<a href=""> <img class='post-group-img' src="/static/images/1.png"></a>
			<small class='text-muted'>	{{post.date_posted.strftime('%Y-%m-%d')}} </small>
			<h1>
			<a href=""> {{post.title}} </a>
			</h1>		
			<p>{{post.content}}</p>

			{%if post.author.username==current_user.username%}
				<a href="{{url_for('posts.update_post', post_id=post.id)}}"> Edit </a>
				<a href="{{url_for('posts.delete_post', post_id=post.id)}}"> Delete </a>
			{%endif%}

		</div>

		</article>
		{%endfor%}

	</div>	



	<div class="col-md-4 post-form-col">
		<form method="POST" action="">
			{{form.hidden_tag()}}
			<fieldset class='form-group'>
				<legend class="border-bottom mb-2"> Post your comment</legend>
				<div class='form-group'>
					{{ form.title.label(class="form-control-label")}}
					{%if form.title.errors %}
						{{ form.title(class="form-control form-control-label-lg is-invalid")}}
						<div class='invalid-feedback'>
							{% for error in form.title.errors%}
								<span>{{error}}</span>
							{%endfor%}
						</div>
					{%else%}
						{{ form.title(class="form-control form-control-label-lg")}}
					{%endif%}
				</div>
				<div class='form-group'>
					{{ form.content.label(class="form-control-label")}}
					{%if form.content.errors %}
						{{ form.content(class="form-control form-control-label-lg is-invalid")}}
						<div class='invalid-feedback'>
							{% for error in form.content.errors%}
								<span>{{error}}</span>
							{%endfor%}
						</div>
					{%else%}
						{{ form.content(class="form-control form-control-label-lg")}}
					{%endif%}				
					
				</div>
			</fieldset>

			<div class='form-group'>
				{{form.submit(class='btn btn-outline-info')}}
			</div>
		</form>
		</div>
	</div>	

{%else%}
<div class='row'>

	<div class="col-md-8 ">
		{% for post in posts.items %}
		<article>
		<div class='container post-group'> 

			<a href=""> <img class='post-group-img' src="/static/images/1.png"></a>
			<small class='text-muted'>	{{post.date_posted.strftime('%Y-%m-%d')}} </small>
			<h1>
			<a href=""> {{post.title}} </a>
			</h1>		
			<p>{{post.content}}</p>
		</div>
		</article>
		{%endfor%}

	</div>	

</div>	

{%endif%}
<div class='row'>
	<div class="col-md-8 search-buttons">
		{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
			{%if posts.page%}
				{%if posts.page==page_num %}
					<a class='btn btn-info mb-4'href="{{url_for('main.home', page=page_num)}}"> {{page_num}} </a>
				{%else%}
					<a class='btn btn-outline-info mb-4'href="{{url_for('main.home', page=page_num)}}"> {{page_num}} </a>
				{% endif %}
			{% endif %}
		{% endfor %}
	</div>
</div>
{%endblock %}

mapapp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	    <meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    	<!-- Bootstrap CSS -->
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    	{% if title %}
        	<title>Flask Blog - {{ title }}</title>
    	{% else %}
        	<title>Flask Blog</title>
    	{% endif %}

	</head>

	<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">

	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
		  <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
		    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
		    {% if current_user.is_authenticated %}
		      <li class="nav-item active">
		        <a class="nav-link" href="{{url_for('main.home')}}"> Home </a>
		      </li>
		      <li class="nav-item active">
		        <a class="nav-link" href="{{url_for('users.account')}}"> Account </a>
		      </li>
		       <li class="nav-item active">
		        <a class="nav-link" href="{{url_for('users.logout')}}"> Log Out </a>
		      </li>
		      {% else %}
		      <li class="nav-item active">
		        <a class="nav-link" href="{{url_for('main.home')}}"> Home </a>
		      </li>
		      <li class="nav-item active">
		        <a class="nav-link" href="{{url_for('users.register')}}"> Register </a>
		      </li>
		       <li class="nav-item active">
		        <a class="nav-link" href="{{url_for('users.login')}}"> Log In </a>
		      </li>
		      {%endif%}
		    </ul>

			  </div>
	  		<a class="navbar-brand mr-4" href="{{url_for('main.home')}}" >
			  	<img src="/static/images/2.png " width=70 height=70 alt="" border-radius="100">
			</a>
	</nav>


		<main role='main' class='container'>
			<!-- <div class="row">
			    <div class="col-md-8"> -->
			    	{% with messages=get_flashed_messages(with_categories=true) %}
			    		{% if messages%}
			    			{% for catagory, message in messages %}
			    				<div class='alert alret={{catagory}}'>
			    					{{message}}
			    				</div>
			    			{%endfor%}
			    		{%endif%}
			    	{%endwith %}
			    	{% block content %}{% endblock %}
<!-- 			    </div> 
		    </div> 	 -->
		</main>
 		
 		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  		  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  		  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	</body>
</html>

mapapp/templates/login.html
{% extends 'layout.html' %}
{% block content %}



<div class='content-section'>

	<div class="col-md-8">
	<form method="POST" action="">
		{{form.hidden_tag()}}
		<fieldset class='form-group'>
			<legend class="border-bottom mb-2"> Join Today</legend>
			<div class='form-group'>
				{{ form.email.label(class="form-control-label")}}
				{%if form.email.errors %}
					{{ form.email(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.email.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.email(class="form-control form-control-label-lg")}}
				{%endif%}				
				
			</div>
			<div class='form-group'>
				{{ form.password.label(class="form-control-label")}}
				{%if form.password.errors %}
					{{ form.password(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.password.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.password(class="form-control form-control-label-lg")}}
				{%endif%}
				
			</div>
		</fieldset>
		<div class='form-check'>
			{{form.remember(class='form-check-input')}}
			{{form.remember.label(class='form-check-label')}}
		</div>
		<div class='form-group'>
			{{form.submit(class='btn btn-outline-info')}}
		</div>
	</form>
	<div class='border-top pt-2'>
		<small class='text-muted'>
			<a href="{{url_for('users.register')}}">Need to Register? </a>
		</small> 
	</div>
	</div>

</div>


{%endblock %}

mapapp/templates/post.html
{% extends 'layout.html' %}
{% block content %}



<div class='content-section'>

	<div class="col-md-8">
	<form method="POST" action="">
		{{form.hidden_tag()}}
		<fieldset class='form-group'>
			<legend class="border-bottom mb-2"> Log In</legend>
			<div class='form-group'>
				{{ form.username.label(class="form-control-label")}}
				{%if form.username.errors %}
					{{ form.username(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.username.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.username(class="form-control form-control-label-lg")}}
				{%endif%}
			</div>
			<div class='form-group'>
				{{ form.email.label(class="form-control-label")}}
				{%if form.email.errors %}
					{{ form.email(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.email.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.email(class="form-control form-control-label-lg")}}
				{%endif%}				
				
			</div>
			<div class='form-group'>
				{{ form.password.label(class="form-control-label")}}
				{%if form.password.errors %}
					{{ form.password(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.password.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.password(class="form-control form-control-label-lg")}}
				{%endif%}
				
			</div>
			<div class='form-group'>
				{{ form.confirm_password.label(class="form-control-label")}}
				{%if form.confirm_password.errors %}
					{{ form.confirm_password(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.confirm_password.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.confirm_password(class="form-control form-control-label-lg")}}
				{%endif%}
				
			</div>
		</fieldset>

		<div class='form-group'>
			{{form.submit(class='btn btn-outline-info')}}
		</div>
	</form>
	<div class='border-top pt-2'>
		<small class='text-muted'>
			Already have an account? <a class='ml-2' href="{{url_for('users.login')}}"> Sign In</a>
		</small> 
	</div>
</div>
</div>


{%endblock %}

mapapp/templates/register.html
{% extends 'layout.html' %}
{% block content %}



<div class='content-section'>

	<div class="col-md-8">
	<form method="POST" action="">
		{{form.hidden_tag()}}
		<fieldset class='form-group'>
			<legend class="border-bottom mb-2"> Log In</legend>
			<div class='form-group'>
				{{ form.username.label(class="form-control-label")}}
				{%if form.username.errors %}
					{{ form.username(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.username.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.username(class="form-control form-control-label-lg")}}
				{%endif%}
			</div>
			<div class='form-group'>
				{{ form.email.label(class="form-control-label")}}
				{%if form.email.errors %}
					{{ form.email(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.email.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.email(class="form-control form-control-label-lg")}}
				{%endif%}				
				
			</div>
			<div class='form-group'>
				{{ form.password.label(class="form-control-label")}}
				{%if form.password.errors %}
					{{ form.password(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.password.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.password(class="form-control form-control-label-lg")}}
				{%endif%}
				
			</div>
			<div class='form-group'>
				{{ form.confirm_password.label(class="form-control-label")}}
				{%if form.confirm_password.errors %}
					{{ form.confirm_password(class="form-control form-control-label-lg is-invalid")}}
					<div class='invalid-feedback'>
						{% for error in form.confirm_password.errors%}
							<span>{{error}}</span>
						{%endfor%}
					</div>
				{%else%}
					{{ form.confirm_password(class="form-control form-control-label-lg")}}
				{%endif%}
				
			</div>
		</fieldset>

		<div class='form-group'>
			{{form.submit(class='btn btn-outline-info')}}
		</div>
	</form>
	<div class='border-top pt-2'>
		<small class='text-muted'>
			Already have an account? <a class='ml-2' href="{{url_for('users.login')}}"> Sign In</a>
		</small> 
	</div>
</div>
</div>


{%endblock %}

mapapp/templates/update_post.html
{% extends 'layout.html' %}
{% block content %}

<div class='row'>
	<div class="col-md-5">
		<form method="POST" action="">
			{{form.hidden_tag()}}
			<fieldset class='form-group'>
				<legend class="border-bottom mb-2"> Update Post </legend>
				<div class='form-group'>
					{{ form.title.label(class="form-control-label")}}
					{%if form.title.errors %}
						{{ form.title(class="form-control form-control-label-lg is-invalid")}}
						<div class='invalid-feedback'>
							{% for error in form.title.errors%}
								<span>{{error}}</span>
							{%endfor%}
						</div>
					{%else%}
						{{ form.title(class="form-control form-control-label-lg")}}
					{%endif%}
				</div>
				<div class='form-group'>
					{{ form.content.label(class="form-control-label")}}
					{%if form.content.errors %}
						{{ form.content(class="form-control form-control-label-lg is-invalid")}}
						<div class='invalid-feedback'>
							{% for error in form.content.errors%}
								<span>{{error}}</span>
							{%endfor%}
						</div>
					{%else%}
						{{ form.content(class="form-control form-control-label-lg")}}
					{%endif%}				
					
				</div>
			</fieldset>

			<div class='form-group'>
				{{form.submit(class='btn btn-outline-info')}}
			</div>
		</form>
	</div>
</div>	


{%endblock %}